package geodata

import "strings"

// CountryName returns a short English name for an ISO 3166-1 alpha-2 code.
func CountryName(code string) string {
	code = strings.ToLower(strings.TrimSpace(code))
	if name, ok := countryNames[code]; ok {
		return name
	}
	if len(code) == 2 {
		return strings.ToUpper(code)
	}
	return ""
}

var countryNames = map[string]string{
	"ad": "Andorra",
	"ae": "United Arab Emirates",
	"af": "Afghanistan",
	"al": "Albania",
	"am": "Armenia",
	"ao": "Angola",
	"ar": "Argentina",
	"at": "Austria",
	"au": "Australia",
	"az": "Azerbaijan",
	"ba": "Bosnia and Herzegovina",
	"bd": "Bangladesh",
	"be": "Belgium",
	"bg": "Bulgaria",
	"bh": "Bahrain",
	"br": "Brazil",
	"by": "Belarus",
	"ca": "Canada",
	"ch": "Switzerland",
	"cl": "Chile",
	"cn": "China",
	"co": "Colombia",
	"cy": "Cyprus",
	"cz": "Czechia",
	"de": "Germany",
	"dk": "Denmark",
	"dz": "Algeria",
	"ee": "Estonia",
	"eg": "Egypt",
	"es": "Spain",
	"fi": "Finland",
	"fr": "France",
	"gb": "United Kingdom",
	"ge": "Georgia",
	"gr": "Greece",
	"hk": "Hong Kong",
	"hr": "Croatia",
	"hu": "Hungary",
	"id": "Indonesia",
	"ie": "Ireland",
	"il": "Israel",
	"in": "India",
	"iq": "Iraq",
	"ir": "Iran",
	"is": "Iceland",
	"it": "Italy",
	"jo": "Jordan",
	"jp": "Japan",
	"ke": "Kenya",
	"kr": "South Korea",
	"kw": "Kuwait",
	"kz": "Kazakhstan",
	"lb": "Lebanon",
	"lk": "Sri Lanka",
	"lt": "Lithuania",
	"lu": "Luxembourg",
	"lv": "Latvia",
	"ly": "Libya",
	"ma": "Morocco",
	"md": "Moldova",
	"mx": "Mexico",
	"my": "Malaysia",
	"ng": "Nigeria",
	"nl": "Netherlands",
	"no": "Norway",
	"np": "Nepal",
	"nz": "New Zealand",
	"om": "Oman",
	"ph": "Philippines",
	"pk": "Pakistan",
	"pl": "Poland",
	"pt": "Portugal",
	"qa": "Qatar",
	"ro": "Romania",
	"rs": "Serbia",
	"ru": "Russia",
	"sa": "Saudi Arabia",
	"se": "Sweden",
	"sg": "Singapore",
	"si": "Slovenia",
	"sk": "Slovakia",
	"sy": "Syria",
	"th": "Thailand",
	"tj": "Tajikistan",
	"tm": "Turkmenistan",
	"tn": "Tunisia",
	"tr": "Turkey",
	"tw": "Taiwan",
	"ua": "Ukraine",
	"uk": "United Kingdom",
	"us": "United States",
	"uz": "Uzbekistan",
	"ve": "Venezuela",
	"vn": "Vietnam",
	"za": "South Africa",
}
